### ISSUE TITLE
Meshes are not syncing properly with physics objects in latest version

### ISSUE THREAD

**Issue by jorjordandan** [pmndrs/react-three-rapier#60] opened 2022-08-17 23:47 UTC
Hello! I ran yarn upgrade on @react-three/rapier today and noticed that it was behaving quite oddly - I made some videos of it on version 0.6.3 (old) and the latest version (new). You can see that the meshes are desyncing from the physics bounds and wobbling around for some reason:

https://www.dropbox.com/scl/fo/99bg75xu9k2o5a08ma8ec/h?dl=0&rlkey=723r3a69flycizmy6oih2w3gh

Assuming it's from here, maybe? 
https://github.com/pmndrs/react-three-rapier/commit/e71ea11d8af62ab31133dc7d82b4b6c726a92256#diff-c7ceb0f2f5cdf0d343ec1c8dc97e80c669fa7e755c722586b60caa26b38a8ff6L219

I would make a PR but there seems to be a lot going on in that commit, ...if I get time later I might try to give it a shot :)

Thanks!

**Comment by Kalmarv** [comment] 2022-08-25 00:22
Definitely a regression, having the same issue.

Here's a reproduction in v0.6.5 - https://codesandbox.io/s/rapier-bug-981yw9

Try changing the version to v0.6.4 and it works fine

**Comment by wiledal** [comment] 2022-08-28 12:25
This is definitely due to the interpolation being applied. We need the interpolation, as it is the proper way to enable deterministic and stable results across devices and framerates, but what you are recording in that video is obviously quite wrong! Seems the high velocity causes trouble.

@jorjordandan, what refresh rate is your screen?

**Comment by jorjordandan** [comment] 2022-08-29 15:24
My monitor is 60hz - Just on an iMac

**Comment by wiledal** [comment] 2022-08-29 18:10
I wonder why this does not happen in my test-sandbox: https://codesandbox.io/s/r3f-rapier-thangs-9x4u1c?file=/src/App.tsx

**Comment by wiledal** [comment] 2022-08-29 18:19
Okay, it looks like the issue is related to the mesh offset rather than just the interpolation. Setting the positions on the `RigidBody` instead of the `mesh` resolves the jittering. Reason still unclear, but I know where to look.

**Comment by Kalmarv** [comment] 2022-08-29 18:24
I don't think it's related the the monitor refresh rate at all, as it happens for me on my 144hz and 240hz

**Comment by wiledal** [comment] 2022-08-29 20:49
Temporarily resolved in v0.6.6, keeping the deterministic fixed frame approach, but bypassing interpolation for translation Will have another crack at the interpolation a later stage, just can't have a jittery mess in the main branch!

**Closed by wiledal** 2022-08-29 20:49 UTC
Labels: bug
